### ISSUE TITLE
Unit tests fail in Python 2.7.10

### ISSUE THREAD

**Issue by TimothyFitz** [rfk/filelike#6]
```
[12:12:43] filelike$ python -m unittest filelike.tests
..........................................F............F...............................
======================================================================
FAIL: test_read_write_read (filelike.tests.Test_ReadWrite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/timothyfitz/Packages/filelike/filelike/tests.py", line 139, in test_read_write_read
    self.assertEquals(c,self.contents[10:15])
AssertionError: '' != 'a tim'

======================================================================
FAIL: test_read_write_read (filelike.tests.Test_ReadWriteSeek)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/timothyfitz/Packages/filelike/filelike/tests.py", line 139, in test_read_write_read
    self.assertEquals(c,self.contents[10:15])
AssertionError: '' != 'a tim'

----------------------------------------------------------------------
Ran 87 tests in 0.025s

FAILED (failures=2)
```

On OS X 10.10.5.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
