### ISSUE TITLE
Fails to install with pip in python3

### ISSUE THREAD

**Issue by JuniorJPDJ** [rfk/filelike#7]
```
>pip3 install filelike
Collecting filelike
  Using cached filelike-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.10.tar.gz
    Extracting in C:\Users\Junior\AppData\Local\Temp\tmpklsbfb00
    Traceback (most recent call last):
      File "c:\users\junior\appdata\local\temp\pip-build-x9g05214\filelike\distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Junior\AppData\Local\Temp\pip-build-x9g05214\filelike\setup.py", line 4, in <module>
        distribute_setup.use_setuptools()
      File "c:\users\junior\appdata\local\temp\pip-build-x9g05214\filelike\distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "c:\users\junior\appdata\local\temp\pip-build-x9g05214\filelike\distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "c:\users\junior\appdata\local\temp\pip-build-x9g05214\filelike\distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "c:\users\junior\appdata\local\temp\pip-build-x9g05214\filelike\distribute_setup.py", line 459, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Junior\AppData\Local\Temp\pip-build-x9g05214\filelike\

```

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
